package com.rsdosev.domain.model

enum class TramStop(val abr: String, val fullName: String) {
    STX ("STX", "St. Stephen's Green"),
    HIN ("HIN", "Heuston"),
    HCT ("HCT", "Heuston"),
    TPT ("TPT", "The Point"),
    SDK ("SDK", "Spencer Dock"),
    MYS ("MYS", "Mayor Square NCI"),
    GDK ("GDK", "George's Dock"),
    CON ("CON", "Connolly"),
    BUS ("BUS", "Busáras"),
    ABB ("ABB", "Abbey Street"),
    JER ("JER", "Jervis"),
    FOU ("FOU", "Four Courts"),
    SMI ("SMI", "Smithfield"),
    MUS ("MUS", "Museum"),
    HEU ("HEU", "Heuston"),
    JAM ("JAM", "James's"),
    FAT ("FAT", "Fatima"),
    RIA ("RIA", "Rialto"),
    SUI ("SUI", "Suir Road"),
    GOL ("GOL", "Goldenbridge"),
    DRI ("DRI", "Drimnagh"),
    BLA ("BLA", "Blackhorse"),
    BLU ("BLU", "Bluebell"),
    KYL ("KYL", "Kylemore"),
    RED ("RED", "Red Cow"),
    KIN ("KIN", "Kingswood"),
    BEL ("BEL", "Belgard"),
    COO ("COO", "Cookstown"),
    HOS ("HOS", "Hospital"),
    TAL ("TAL", "Tallaght"),
    FET ("FET", "Fettercairn"),
    CVN ("CVN", "Cheeverstown"),
    CIT ("CIT", "Citywest Campus"),
    FOR ("FOR", "Fortunestown"),
    SAG ("SAG", "Saggart"),
    DEP ("DEP", "Depot"),
    BRO ("BRO", "Broombridge"),
    CAB ("CAB", "Cabra"),
    PHI ("PHI", "Phibsborough"),
    GRA ("GRA", "Grangegorman"),
    BRD ("BRD", "Broadstone DIT"),
    DOM ("DOM", "Dominick"),
    PAR ("PAR", "Parnell"),
    OUP ("OUP", "O'Connell Upper"),
    OGP ("OGP", "O'Connell GPO"),
    MAR ("MAR", "Marlborough"),
    WES ("WES", "Westmoreland"),
    TRY ("TRY", "Trinity"),
    DAW ("DAW", "Dawson"),
    STS ("STS", "St. Stephen's Green"),
    HAR ("HAR", "Harcourt"),
    CHA ("CHA", "Charlemont"),
    RAN ("RAN", "Ranelagh"),
    BEE ("BEE", "Beechwood"),
    COW ("COW", "Cowper"),
    MIL ("MIL", "Milltown"),
    WIN ("WIN", "Windy Arbour"),
    DUN ("DUN", "Dundrum"),
    BAL ("BAL", "Balally"),
    KIL ("KIL", "Kilmacud"),
    STI ("STI", "Stillorgan"),
    SAN ("SAN", "Sandyford"),
    CPK ("CPK", "Central Park"),
    GLE ("GLE", "Glencairn"),
    GAL ("GAL", "The Gallops"),
    LEO ("LEO", "Leopardstown Valley"),
    BAW ("BAW", "Ballyogan Wood"),
    RCC ("RCC", "Racecourse"),
    CCK ("CCK", "Carrickmines"),
    BRE ("BRE", "Brennanstown"),
    LAU ("LAU", "Laughanstown"),
    CHE ("CHE", "Cherrywood"),
    BRI ("BRI", "Bride's Glen")
}